# Generated by Django 5.0 on 2023-12-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_readers_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='readers',
            name='status',
            field=models.CharField(choices=[('NW', 'New'), ('AC', 'Active')], default='NW', max_length=2),
        ),
    ]
