# Generated by Django 5.0 on 2024-01-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_edited',
            field=models.BooleanField(default=False),
        ),
    ]
