# Generated by Django 5.0 on 2024-01-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0006_payment_payment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readers',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active')], default='New', max_length=6),
        ),
    ]
