# Generated by Django 5.0 on 2024-01-02 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0007_alter_readers_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_payee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
